// Generated by CoffeeScript 1.3.3
(function() {
  var $, $$, RandomString;

  $$ = window.BASE = window.BASE || {};

  $ = window.jQuery;

  RandomString = (function() {
    /**
     * [constructor description]
     * @param  {[type]} legalCharList [description]
     * @return {[type]}               [description]
    */

    function RandomString(legalCharList) {
      var defaultLegalChar;
      defaultLegalChar = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      if (legalCharList) {
        this.legalCharList = legalCharList.split("");
      } else {
        this.legalCharList = defaultLegalChar.split("");
      }
      this.legalListLength = this.legalCharList.length;
    }

    /**
     * [getRandomStr description]
     * @param  {[type]} len [description]
     * @return {[type]}     [description]
    */


    RandomString.prototype.getRandomStr = function(len) {
      var num;
      if (len == null) {
        len = 10;
      }
      return ((function() {
        var _i, _results;
        _results = [];
        for (num = _i = 1; _i <= 10; num = ++_i) {
          _results.push(this.getRandomChar(num));
        }
        return _results;
      }).call(this)).join("");
    };

    /**
     * [getRandomChar description]
     * @return {[type]} [description]
    */


    RandomString.prototype.getRandomChar = function() {
      return this.legalCharList[Math.floor(Math.random() * this.legalListLength)];
    };

    return RandomString;

  })();

  $.extend($$, {
    version: "0.8.1",
    msie6: $.browser.msie && $.browser.version === "6.0",
    defaultAnimateDuration: 300,
    defaultBorder: "uiBlueBorder",
    defaultBoxShadow: "uiBlueBoxShadow",
    defaultGradientBG: "uiBlueGradientBG",
    hoverGradientBG: "uiLightBlueGradientBG",
    selectedGradientBG: "uiRedGradientBG",
    cssShow: {
      position: "absolute",
      visibility: "hidden",
      display: "block"
    },
    widgetType: {
      uiDialog: "dialog",
      uiTabs: "tabs",
      uiSlide: "slide",
      uiAccordion: "accordion",
      uiButtonSet: "buttonSet",
      uiDorpDownList: "dropDownList",
      uiProgressBar: "progressBar",
      uiTip: "tip",
      uiList: "list",
      uiDatePicker: "datePicker",
      uiTree: "tree",
      uiGrid: "grid"
    },
    /**
     * [widgetDictionary description]
     * @type {Object}
    */

    widgetDictionary: {},
    /**
     * [randomKey description]
     * @type {RandomString}
    */

    randomKey: new RandomString(),
    /**
     * [getWidget description]
     * @param  {[type]} key [description]
     * @return {[type]}     [description]
    */

    getWidget: function(key) {
      var widget;
      widget = this.widgetDictionary[key];
      if (widget != null) {
        return widget;
      }
    },
    /**
     * [addWidget description]
     * @param {[type]} key    [description]
     * @param {[type]} widget [description]
    */

    addWidget: function(key, widget) {
      if ((key != null) && (widget != null)) {
        return this.widgetDictionary[key] = widget;
      }
    },
    /**
     * [removeWidget description]
     * @param  {[type]} key [description]
     * @return {[type]}     [description]
    */

    removeWidget: function(key) {
      var opts, prop, widget;
      widget = this.widgetDictionary[key];
      if (!delete this.widgetDictionary[key]) {
        this.widgetDictionary[key] = null;
      }
      if (widget != null) {
        opts = widget.opts;
      }
      for (prop in opts) {
        if (opts.hasOwnProperty(prop)) {
          if (!(delete opts[prop])) {
            opts[prop] = null;
          }
        }
      }
      for (prop in widget) {
        if (widget.hasOwnProperty(prop)) {
          if (!(delete widget[prop])) {
            widget[prop] = null;
          }
        }
      }
      return true;
    },
    /**
     * [getRandomKey description]
     * @param  {[type]} length [description]
     * @return {[type]}        [description]
    */

    getRandomKey: function(length) {
      return this.randomKey.getRandomStr(length);
    },
    /**
     * [createWidgetByJQuery description]
     * @return {[type]} [description]
    */

    createWidgetByJQuery: function() {
      var args, constructor, options, self, widgetKey, widgetObj;
      self = this;
      args = Array.prototype.slice.call(arguments);
      constructor = args.pop();
      options = args[0];
      if (typeof options === "string") {
        widgetKey = self.attr("widget");
        if (widgetKey != null) {
          widgetObj = $$.getWidget(widgetKey);
          return widgetObj.selectHandle.apply(widgetObj, args);
        }
      } else {
        widgetObj = new constructor(self, options);
      }
      return self;
    }
  });

}).call(this);
